spring.jpa.hibernate.ddl-auto: create-drop
spring.datasource.url: jdbc:mysql://localhost:3306/java_angular?serverTimezone=UTC&useSSL=false&autoReconnect=true
spring.datasource.username: root
spring.datasource.password: cybersecurity